name: CI - FacelessLogger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, json, pcov
          coverage: pcov
          tools: composer, phpunit

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run static analysis
        run: |
          if [ -f vendor/bin/phpstan ]; then
            vendor/bin/phpstan analyse src --level=max || true
          else
            echo "phpstan not installed — skipping"
          fi

      - name: Run test suite with coverage
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --colors=always --coverage-clover=build/logs/clover.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/logs/clover.xml
          fail_ci_if_error: true
          verbose: true

      - name: Display coverage summary
        run: |
          if [ -f build/logs/clover.xml ]; then
            echo "✅ Coverage file generated successfully!"
          else
            echo "❌ Coverage file missing!"
            exit 1
          fi
